-- =========================
-- CREATE TABLE
-- =========================

CREATE TABLE FILM (
    ID_FILM CHAR(5) PRIMARY KEY,
    JUDUL VARCHAR2(100) NOT NULL,
    DURASI NUMBER(3),
    TAHUN_RILIS NUMBER(4),
    SINOPSIS CLOB
);

CREATE TABLE TEATER (
    ID_TEATER CHAR(3) PRIMARY KEY,
    NAMA_TEATER VARCHAR2(30),
    KELAS VARCHAR2(20),
    HARGA NUMBER(8),
    KAPASITAS NUMBER(3)
);

CREATE TABLE MEMBER_BIOSKOP (
    ID_MEMBER CHAR(6) PRIMARY KEY,
    NAMA_MEMBER VARCHAR2(50),
    NO_HP VARCHAR2(15),
    EMAIL VARCHAR2(50),
    TGL_LAHIR DATE
);

CREATE TABLE JADWAL_TAYANG (
    ID_JADWAL CHAR(5) PRIMARY KEY,
    ID_FILM CHAR(5),
    ID_TEATER CHAR(3),
    PERIODE_START DATE,
    PERIODE_END DATE,
    CONSTRAINT FK_FILM
        FOREIGN KEY (ID_FILM)
        REFERENCES FILM(ID_FILM),
    CONSTRAINT FK_TEATER
        FOREIGN KEY (ID_TEATER)
        REFERENCES TEATER(ID_TEATER)
);

CREATE TABLE KURSI (
    ID_KURSI CHAR(6) PRIMARY KEY,
    ID_TEATER CHAR(3),
    NOMOR_KURSI VARCHAR2(5),
    CONSTRAINT FK_KURSI_TEATER
        FOREIGN KEY (ID_TEATER)
        REFERENCES TEATER(ID_TEATER)
);

CREATE TABLE PEMESANAN (
    ID_PESAN CHAR(6) PRIMARY KEY,
    ID_MEMBER CHAR(6),
    ID_JADWAL CHAR(5),
    ID_KURSI CHAR(6),
    TGL_PESAN DATE,
    STATUS_PESAN VARCHAR2(20),
    CONSTRAINT FK_MEMBER
        FOREIGN KEY (ID_MEMBER)
        REFERENCES MEMBER_BIOSKOP(ID_MEMBER),
    CONSTRAINT FK_JADWAL
        FOREIGN KEY (ID_JADWAL)
        REFERENCES JADWAL_TAYANG(ID_JADWAL),
    CONSTRAINT FK_KURSI
        FOREIGN KEY (ID_KURSI)
        REFERENCES KURSI(ID_KURSI)
);

-- =========================
-- INSERT DATA
-- =========================

-- INSERT FILM
INSERT INTO FILM 
VALUES ('F0001', 'Avengers Endgame', 181, 2019, 'Film superhero Marvel');

INSERT INTO FILM 
VALUES ('F0002', 'Frozen 2', 103, 2019, 'Film animasi Disney');

-- INSERT TEATER
INSERT INTO TEATER 
VALUES ('T01', 'XXI Rita', 'Regular', 50000, 150);

INSERT INTO TEATER 
VALUES ('T02', 'CGV Moro', 'VIP', 75000, 100);

-- INSERT MEMBER_BIOSKOP
INSERT INTO MEMBER_BIOSKOP 
VALUES ('M00001', 'Andini', '08123456789', 'andini@gmail.com', TO_DATE('21-01-2007','DD-MM-YYYY'));

INSERT INTO MEMBER_BIOSKOP 
VALUES ('M00002', 'Budi', '08987654321', 'budi@gmail.com', TO_DATE('15-08-2005','DD-MM-YYYY'));

-- INSERT JADWAL_TAYANG
INSERT INTO JADWAL_TAYANG 
VALUES ('J0001', 'F0001', 'T01', TO_DATE('01-05-2026','DD-MM-YYYY'), TO_DATE('07-05-2026','DD-MM-YYYY'));

INSERT INTO JADWAL_TAYANG 
VALUES ('J0002', 'F0002', 'T02', TO_DATE('08-05-2026','DD-MM-YYYY'), TO_DATE('14-05-2026','DD-MM-YYYY'));

-- INSERT KURSI
INSERT INTO KURSI 
VALUES ('K00001', 'T01', 'A01');

INSERT INTO KURSI 
VALUES ('K00002', 'T02', 'B01');

-- INSERT PEMESANAN
INSERT INTO PEMESANAN 
VALUES ('P00001', 'M00001', 'J0001', 'K00001', SYSDATE, 'LUNAS');

INSERT INTO PEMESANAN 
VALUES ('P00002', 'M00002', 'J0002', 'K00002', SYSDATE, 'PENDING');

commit;

SELECT * FROM FILM;
SELECT * FROM TEATER;
SELECT * FROM MEMBER_BIOSKOP;
SELECT * FROM JADWAL_TAYANG;
SELECT * FROM KURSI;
SELECT * FROM PEMESANAN;

-- =========================
-- UPDATE DATA (5 DATA)
-- =========================

-- CEK DATA SEBELUM UPDATE
SELECT * FROM FILM;
SELECT * FROM TEATER;
SELECT * FROM MEMBER_BIOSKOP;
SELECT * FROM KURSI;
SELECT * FROM PEMESANAN;

-- UPDATE 1
UPDATE FILM
SET DURASI = 190
WHERE ID_FILM = 'F0001';

-- UPDATE 2
UPDATE TEATER
SET HARGA = 80000
WHERE ID_TEATER = 'T02';

-- UPDATE 3
UPDATE MEMBER_BIOSKOP
SET NAMA_MEMBER = 'Andini Putri'
WHERE ID_MEMBER = 'M00001';

-- UPDATE 4
UPDATE KURSI
SET NOMOR_KURSI = 'A02'
WHERE ID_KURSI = 'K00001';

-- UPDATE 5
UPDATE PEMESANAN
SET STATUS_PESAN = 'SELESAI'
WHERE ID_PESAN = 'P00002';

SELECT * FROM FILM;
SELECT * FROM TEATER;
SELECT * FROM MEMBER_BIOSKOP;
SELECT * FROM KURSI;
SELECT * FROM PEMESANAN;

-- =========================
-- DELETE DATA (2 DATA)
-- =========================

-- DELETE 1
DELETE FROM PEMESANAN
WHERE ID_PESAN = 'P00002';

-- DELETE 2
DELETE FROM KURSI
WHERE ID_KURSI = 'K00002';

-- CEK DATA SETELAH DELETE
SELECT * FROM KURSI;
SELECT * FROM PEMESANAN;