CREATE TABLE FILM (
    ID_FILM CHAR(5) PRIMARY KEY,
    JUDUL VARCHAR2(100) NOT NULL,
    DURASI NUMBER(3),
    TAHUN_RILIS NUMBER(4),
    SINOPSIS CLOB
);

CREATE TABLE TEATER (
    ID_TEATER CHAR(3) PRIMARY KEY,
    NAMA_TEATER VARCHAR2(30),
    KELAS VARCHAR2(20),
    HARGA NUMBER(8),
    KAPASITAS NUMBER(3)
);

CREATE TABLE MEMBER_BIOSKOP (
    ID_MEMBER CHAR(6) PRIMARY KEY,
    NAMA_MEMBER VARCHAR2(50),
    NO_HP VARCHAR2(15),
    EMAIL VARCHAR2(50),
    TGL_LAHIR DATE
);

CREATE TABLE JADWAL_TAYANG (
    ID_JADWAL CHAR(5) PRIMARY KEY,
    ID_FILM CHAR(5),
    ID_TEATER CHAR(3),
    PERIODE_START DATE,
    PERIODE_END DATE,
    CONSTRAINT FK_FILM
        FOREIGN KEY (ID_FILM)
        REFERENCES FILM(ID_FILM),
    CONSTRAINT FK_TEATER
        FOREIGN KEY (ID_TEATER)
        REFERENCES TEATER(ID_TEATER)
);

CREATE TABLE KURSI (
    ID_KURSI CHAR(6) PRIMARY KEY,
    ID_TEATER CHAR(3),
    NOMOR_KURSI VARCHAR2(5),
    CONSTRAINT FK_KURSI_TEATER
        FOREIGN KEY (ID_TEATER)
        REFERENCES TEATER(ID_TEATER)
);

CREATE TABLE PEMESANAN (
    ID_PESAN CHAR(6) PRIMARY KEY,
    ID_MEMBER CHAR(6),
    ID_JADWAL CHAR(5),
    ID_KURSI CHAR(6),
    TGL_PESAN DATE,
    STATUS_PESAN VARCHAR2(20),
    CONSTRAINT FK_MEMBER
        FOREIGN KEY (ID_MEMBER)
        REFERENCES MEMBER_BIOSKOP(ID_MEMBER),
    CONSTRAINT FK_JADWAL
        FOREIGN KEY (ID_JADWAL)
        REFERENCES JADWAL_TAYANG(ID_JADWAL),
    CONSTRAINT FK_KURSI
        FOREIGN KEY (ID_KURSI)
        REFERENCES KURSI(ID_KURSI)
);