SELECT 
    fl.JUDUL,
    jd.ID_THEATER AS NOMOR_TEATER,
    COUNT(jd.ID_JADWAL) AS JUMLAH_DIPUTAR
FROM FILM_103122400060 fl
INNER JOIN JADWAL_103122400060 jd
ON fl.ID_FILM = jd.ID_FILM
WHERE fl.JUDUL = 'Habibie Ainun 3'
GROUP BY fl.JUDUL, jd.ID_THEATER
ORDER BY JUMLAH_DIPUTAR DESC;